@host=https://3001-scarlet-albatross-j6d53h3q.ws-us11.gitpod.io/api

### Creacion de Hash
POST {{host}}/hash
Content-Type: application/json


### REGISTER
POST {{host}}/register
Content-Type: application/json

{
    "email":"apo@lo.cl",
    "password":"PASSword",
    "username":"apolo"
}

# {
#     "email":"hola@ortega.cl",
#     "password":"87654321",
#     "username":"manu"
# }



###  @AUTH
# @name authSession
POST {{host}}/login
Content-Type: application/json

{
    "email":"hola@ortega.cl",
    "password":"87654321"
}

###
@token = {{authSession.response.body.$.token}}



### USER
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

